"""
Simulation Module - Version 4.0

Comprehensive simulation capabilities for pub-sub systems working directly
on the graph model without requiring Neo4j or DEPENDS_ON relationships.

Simulators:
- FailureSimulator: Component failure and cascade simulation
- EventSimulator: Discrete event message flow simulation

Usage:
    from src.simulation import SimulationGraph, FailureSimulator, EventSimulator

    # Load graph from JSON (generated by generate_graph.py)
    graph = SimulationGraph.from_json("system.json")
    
    # Failure simulation
    fail_sim = FailureSimulator(cascade_threshold=0.5)
    result = fail_sim.simulate_failure(graph, "broker_0")
    print(f"Impact score: {result.impact.impact_score:.4f}")
    
    # Exhaustive campaign
    batch = fail_sim.simulate_all_failures(graph)
    for comp, impact in batch.critical_components[:5]:
        print(f"{comp}: {impact:.4f}")
    
    # Event-driven simulation
    event_sim = EventSimulator()
    result = event_sim.simulate(graph, duration_ms=10000, message_rate=100)
    print(f"Delivery rate: {result.metrics.delivery_rate():.1%}")
    
    # Load testing
    result = event_sim.simulate_load_test(
        graph, initial_rate=10, peak_rate=500, ramp_time_ms=5000
    )
    
    # Chaos engineering
    result = event_sim.simulate_chaos(
        graph, failure_probability=0.01, recovery_probability=0.1
    )

Author: Software-as-a-Graph Research Project
Version: 4.0
"""

# Graph Model
from .graph_model import (
    SimulationGraph,
    Component,
    Connection,
    ComponentType,
    ConnectionType,
)

# Failure Simulator
from .failure_simulator import (
    FailureSimulator,
    FailureType,
    FailureMode,
    AttackStrategy,
    FailureEvent,
    ImpactMetrics,
    SimulationResult as FailureResult,
    BatchResult,
)

# Event-Driven Simulator
from .event_simulator import (
    EventSimulator,
    EventType,
    MessageState,
    QoSLevel,
    SimEvent,
    Message,
    ComponentStats,
    SimMetrics,
    SimulationResult as EventResult,
)

__all__ = [
    # Graph Model
    "SimulationGraph",
    "Component",
    "Connection",
    "ComponentType",
    "ConnectionType",
    # Failure Simulator
    "FailureSimulator",
    "FailureType",
    "FailureMode",
    "AttackStrategy",
    "FailureEvent",
    "ImpactMetrics",
    "FailureResult",
    "BatchResult",
    # Event Simulator
    "EventSimulator",
    "EventType",
    "MessageState",
    "QoSLevel",
    "SimEvent",
    "Message",
    "ComponentStats",
    "SimMetrics",
    "EventResult",
]

__version__ = "4.0.0"