"""
Dashboard Generator

Constructs a responsive HTML dashboard.
Includes layout for KPIs, Charts, Tables, and Validation Metrics.
"""

from datetime import datetime
from typing import List, Dict, Any, Optional
from .charts import ChartOutput

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        :root {{ --primary: #2c3e50; --secondary: #34495e; --accent: #3498db; --danger: #e74c3c; --success: #2ecc71; --bg: #f4f6f7; }}
        body {{ font-family: 'Segoe UI', Roboto, sans-serif; margin: 0; background: var(--bg); color: #2c3e50; padding-top: 60px; }}
        
        /* Navigation */
        nav {{ position: fixed; top: 0; width: 100%; background: var(--primary); color: white; z-index: 1000; box-shadow: 0 2px 5px rgba(0,0,0,0.2); }}
        .nav-container {{ max-width: 1200px; margin: 0 auto; display: flex; justify-content: space-between; align-items: center; padding: 0 20px; height: 60px; }}
        .nav-logo {{ font-weight: bold; font-size: 1.2rem; }}
        .nav-links a {{ color: #bdc3c7; text-decoration: none; margin-left: 20px; font-size: 0.9rem; transition: color 0.3s; }}
        .nav-links a:hover {{ color: white; }}
        
        .container {{ max-width: 1200px; margin: 2rem auto; padding: 0 20px; }}
        
        h1 {{ text-align: center; color: var(--primary); margin-bottom: 0.5rem; }}
        .meta {{ text-align: center; color: #7f8c8d; font-size: 0.9rem; margin-bottom: 2rem; }}
        
        .section {{ background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.05); margin-bottom: 2rem; scroll-margin-top: 80px; }}
        .section-header {{ border-left: 5px solid var(--accent); padding-left: 15px; margin-top: 0; margin-bottom: 25px; color: var(--primary); font-size: 1.5rem; }}
        
        /* KPIs */
        .kpi-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin-bottom: 30px; }}
        .kpi-card {{ background: linear-gradient(135deg, var(--secondary), var(--primary)); color: white; padding: 20px; border-radius: 8px; text-align: center; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }}
        .kpi-val {{ font-size: 2.2rem; font-weight: 700; margin-bottom: 5px; }}
        .kpi-label {{ font-size: 0.85rem; text-transform: uppercase; opacity: 0.9; letter-spacing: 1px; }}
        
        /* Charts */
        .chart-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(450px, 1fr)); gap: 30px; margin-bottom: 30px; }}
        .chart-card {{ border: 1px solid #ecf0f1; padding: 15px; border-radius: 8px; text-align: center; background: #fff; }}
        .chart-card h4 {{ margin-top: 0; color: var(--secondary); font-size: 1.1rem; }}
        img {{ max-width: 100%; height: auto; border-radius: 4px; }}
        
        /* Tables */
        table {{ width: 100%; border-collapse: collapse; margin-top: 15px; font-size: 0.9rem; }}
        th, td {{ padding: 12px 15px; border-bottom: 1px solid #ecf0f1; text-align: left; }}
        th {{ background: #f8f9fa; color: var(--secondary); font-weight: 600; text-transform: uppercase; font-size: 0.8rem; }}
        tr:hover {{ background-color: #f9f9f9; }}
        .badge {{ padding: 4px 10px; border-radius: 20px; color: white; font-size: 0.75rem; font-weight: bold; display: inline-block; }}
        
        /* Metrics Box */
        .metrics-box {{ background: #f8f9fa; padding: 20px; border-radius: 8px; border: 1px solid #e9ecef; margin-bottom: 30px; }}
        .metric-row {{ display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px dashed #dee2e6; }}
        .metric-row:last-child {{ border-bottom: none; }}
        .metric-name {{ font-weight: 600; color: #555; }}
        .metric-val {{ font-family: 'Consolas', monospace; font-weight: bold; color: var(--accent); }}
        .pass {{ color: var(--success); }}
        .fail {{ color: var(--danger); }}
        
        .footer {{ text-align: center; color: #bdc3c7; padding: 40px 0; font-size: 0.8rem; }}
    </style>
</head>
<body>
    <nav>
        <div class="nav-container">
            <div class="nav-logo">SaaG Dashboard</div>
            <div class="nav-links">
                <a href="#stats">Statistics</a>
                <a href="#complete">Complete System</a>
                <a href="#application">Application</a>
                <a href="#infrastructure">Infrastructure</a>
            </div>
        </div>
    </nav>
    
    <div class="container">
        <h1>{title}</h1>
        <div class="meta">Generated: {timestamp}</div>
        {content}
    </div>
    
    <div class="footer">Generated by Software-as-a-Graph Visualization Module</div>
</body>
</html>
"""

class DashboardGenerator:
    def __init__(self, title: str):
        self.title = title
        self.sections = []

    def start_section(self, title: str, anchor_id: str = ""):
        id_attr = f' id="{anchor_id}"' if anchor_id else ""
        self.sections.append(f'<div class="section"{id_attr}><h2 class="section-header">{title}</h2>')

    def end_section(self):
        self.sections.append('</div>')

    def add_kpis(self, kpis: Dict[str, Any]):
        html = ['<div class="kpi-grid">']
        for k, v in kpis.items():
            html.append(f'<div class="kpi-card"><div class="kpi-val">{v}</div><div class="kpi-label">{k}</div></div>')
        html.append('</div>')
        self.sections.append("".join(html))

    def add_metrics_table(self, metrics: Dict[str, Any], title: str = "Validation Metrics"):
        html = [f'<h3>{title}</h3><div class="metrics-box">']
        for k, v in metrics.items():
            val_display = v
            cls = ""
            
            if isinstance(v, float):
                val_display = f"{v:.4f}"
            
            if k.lower() == "status":
                cls = "pass" if v == "PASSED" else "fail"
            
            html.append(f'<div class="metric-row"><span class="metric-name">{k}</span><span class="metric-val {cls}">{val_display}</span></div>')
        html.append('</div>')
        self.sections.append("".join(html))

    def add_charts(self, charts: List[ChartOutput]):
        valid_charts = [c for c in charts if c]
        if not valid_charts: return
        
        html = ['<div class="chart-grid">']
        for c in valid_charts:
            html.append(
                f'<div class="chart-card">'
                f'<h4>{c.title}</h4>'
                f'<img src="data:image/png;base64,{c.png_base64}" alt="{c.title}">'
                f'<p style="color:#7f8c8d;font-size:0.8rem;margin-top:10px">{c.description}</p>'
                f'</div>'
            )
        html.append('</div>')
        self.sections.append("".join(html))

    def add_table(self, headers: List[str], rows: List[List[Any]]):
        html = ['<div style="overflow-x:auto;"><table><thead><tr>']
        for h in headers: html.append(f'<th>{h}</th>')
        html.append('</tr></thead><tbody>')
        
        for row in rows:
            html.append('<tr>')
            for cell in row:
                val = str(cell)
                # Badge coloring logic
                style = ""
                if val == "CRITICAL": style = "background:#e74c3c"
                elif val == "HIGH": style = "background:#e67e22"
                elif val == "MEDIUM": style = "background:#f1c40f;color:#333"
                elif val == "LOW": style = "background:#2ecc71"
                
                content = f'<span class="badge" style="{style}">{val}</span>' if style else val
                html.append(f'<td>{content}</td>')
            html.append('</tr>')
        html.append('</tbody></table></div>')
        self.sections.append("".join(html))

    def generate(self) -> str:
        return HTML_TEMPLATE.format(
            title=self.title,
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            content="\n".join(self.sections)
        )