"""
Dashboard Generator

Constructs a responsive HTML dashboard.
"""

from datetime import datetime
from typing import List, Dict, Any
from .charts import ChartOutput

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        :root {{ --primary: #2c3e50; --secondary: #34495e; --accent: #3498db; --danger: #e74c3c; }}
        body {{ font-family: 'Segoe UI', sans-serif; margin: 0; background: #f4f6f7; color: #2c3e50; }}
        .container {{ max-width: 1200px; margin: 0 auto; padding: 20px; }}
        
        header {{ background: white; border-bottom: 4px solid var(--primary); padding: 2rem; text-align: center; margin-bottom: 2rem; }}
        h1 {{ margin: 0; color: var(--primary); }}
        .meta {{ color: #7f8c8d; font-size: 0.9rem; margin-top: 10px; }}
        
        .section {{ background: white; padding: 25px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.05); margin-bottom: 2rem; }}
        .section-header {{ border-left: 5px solid var(--accent); padding-left: 15px; margin-bottom: 20px; color: var(--primary); }}
        
        .kpi-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 15px; margin-bottom: 30px; }}
        .kpi-card {{ background: var(--secondary); color: white; padding: 15px; border-radius: 6px; text-align: center; }}
        .kpi-val {{ font-size: 2rem; font-weight: bold; }}
        .kpi-label {{ font-size: 0.8rem; text-transform: uppercase; opacity: 0.9; }}
        
        .chart-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(500px, 1fr)); gap: 20px; }}
        .chart-card {{ border: 1px solid #eee; padding: 15px; border-radius: 6px; text-align: center; }}
        img {{ max-width: 100%; height: auto; }}
        
        table {{ width: 100%; border-collapse: collapse; margin-top: 15px; font-size: 0.9rem; }}
        th, td {{ padding: 10px; border-bottom: 1px solid #eee; text-align: left; }}
        th {{ background: #ecf0f1; }}
        .badge {{ padding: 3px 8px; border-radius: 12px; color: white; font-size: 0.75rem; font-weight: bold; }}
        
        .footer {{ text-align: center; color: #bdc3c7; padding: 20px; font-size: 0.8rem; }}
    </style>
</head>
<body>
    <header>
        <div class="container">
            <h1>{title}</h1>
            <div class="meta">Generated: {timestamp}</div>
        </div>
    </header>
    <div class="container">
        {content}
    </div>
    <div class="footer">Generated by Software-as-a-Graph Visualization Module</div>
</body>
</html>
"""

class DashboardGenerator:
    def __init__(self, title: str):
        self.title = title
        self.sections = []

    def start_section(self, title: str):
        self.sections.append(f'<div class="section"><h2 class="section-header">{title}</h2>')

    def end_section(self):
        self.sections.append('</div>')

    def add_kpis(self, kpis: Dict[str, Any]):
        html = ['<div class="kpi-grid">']
        for k, v in kpis.items():
            html.append(f'<div class="kpi-card"><div class="kpi-val">{v}</div><div class="kpi-label">{k}</div></div>')
        html.append('</div>')
        self.sections.append("".join(html))

    def add_charts(self, charts: List[ChartOutput]):
        if not charts: return
        html = ['<div class="chart-grid">']
        for c in charts:
            if c:
                html.append(f'<div class="chart-card"><h4>{c.title}</h4><img src="data:image/png;base64,{c.png_base64}"><p style="color:#777;font-size:0.8rem">{c.description}</p></div>')
        html.append('</div>')
        self.sections.append("".join(html))

    def add_table(self, headers: List[str], rows: List[List[Any]]):
        html = ['<div style="overflow-x:auto;"><table><thead><tr>']
        for h in headers: html.append(f'<th>{h}</th>')
        html.append('</tr></thead><tbody>')
        
        for row in rows:
            html.append('<tr>')
            for cell in row:
                val = str(cell)
                # Simple badge coloring logic
                style = ""
                if val == "CRITICAL": style = "background:#e74c3c"
                elif val == "HIGH": style = "background:#e67e22"
                elif val == "MEDIUM": style = "background:#f1c40f;color:#333"
                elif val == "LOW": style = "background:#2ecc71"
                
                content = f'<span class="badge" style="{style}">{val}</span>' if style else val
                html.append(f'<td>{content}</td>')
            html.append('</tr>')
        html.append('</tbody></table></div>')
        self.sections.append("".join(html))

    def generate(self) -> str:
        return HTML_TEMPLATE.format(
            title=self.title,
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            content="\n".join(self.sections)
        )