"""
Dashboard Generator

Constructs a responsive HTML dashboard visualizing multi-layer analysis.
"""

from datetime import datetime
from typing import List, Dict, Any
from .charts import ChartOutput

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        :root {{ --primary: #2c3e50; --secondary: #34495e; --accent: #3498db; --danger: #e74c3c; --light: #ecf0f1; }}
        body {{ font-family: 'Segoe UI', system-ui, sans-serif; margin: 0; background: #f8f9fa; color: #333; }}
        .container {{ max-width: 1200px; margin: 0 auto; padding: 20px; }}
        
        header {{ background: var(--primary); color: white; padding: 2rem; border-radius: 8px 8px 0 0; margin-bottom: 2rem; }}
        h1 {{ margin: 0; font-size: 2rem; }}
        .subtitle {{ opacity: 0.8; margin-top: 0.5rem; }}
        
        .section {{ background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.05); margin-bottom: 2rem; }}
        .section-title {{ border-bottom: 2px solid var(--accent); color: var(--primary); padding-bottom: 10px; margin-bottom: 20px; }}
        
        .kpi-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin-bottom: 20px; }}
        .kpi-card {{ background: var(--accent); color: white; padding: 15px; border-radius: 6px; text-align: center; }}
        .kpi-val {{ font-size: 2rem; font-weight: bold; }}
        .kpi-label {{ font-size: 0.9rem; text-transform: uppercase; letter-spacing: 1px; }}
        
        .chart-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(500px, 1fr)); gap: 20px; }}
        .chart-card {{ border: 1px solid #eee; padding: 10px; border-radius: 4px; text-align: center; }}
        img {{ max-width: 100%; height: auto; }}
        
        table {{ width: 100%; border-collapse: collapse; font-size: 0.9rem; }}
        th, td {{ padding: 12px 15px; text-align: left; border-bottom: 1px solid #eee; }}
        th {{ background: var(--secondary); color: white; }}
        tr:hover {{ background: #f1f1f1; }}
        .badge {{ padding: 4px 8px; border-radius: 4px; font-size: 0.8rem; font-weight: bold; }}
        .bg-crit {{ background: #fadbd8; color: #c0392b; }}
        .bg-high {{ background: #fdebd0; color: #d35400; }}
        .bg-ok {{ background: #d4efdf; color: #27ae60; }}
        
        footer {{ text-align: center; color: #7f8c8d; padding: 20px; font-size: 0.85rem; }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>{title}</h1>
            <div class="subtitle">Software-as-a-Graph Analysis Report | Generated: {timestamp}</div>
        </header>
        
        {content}
        
        <footer>
            Generated by Software-as-a-Graph Visualization Module
        </footer>
    </div>
</body>
</html>
"""

class DashboardGenerator:
    def __init__(self, title: str = "System Analysis Dashboard"):
        self.title = title
        self.sections = []

    def add_section_header(self, title: str):
        self.sections.append(f'<div class="section"><h2 class="section-title">{title}</h2>')

    def close_section(self):
        self.sections.append('</div>')

    def add_kpis(self, kpis: Dict[str, Any]):
        html = ['<div class="kpi-grid">']
        for label, val in kpis.items():
            html.append(f"""
                <div class="kpi-card">
                    <div class="kpi-val">{val}</div>
                    <div class="kpi-label">{label}</div>
                </div>
            """)
        html.append('</div>')
        self.sections.append("".join(html))

    def add_charts(self, charts: List[ChartOutput]):
        if not charts: return
        html = ['<div class="chart-grid">']
        for chart in charts:
            html.append(f"""
                <div class="chart-card">
                    <h3>{chart.title}</h3>
                    <img src="data:image/png;base64,{chart.png_base64}" alt="{chart.title}"/>
                    <p>{chart.description}</p>
                </div>
            """)
        html.append('</div>')
        self.sections.append("".join(html))

    def add_table(self, headers: List[str], rows: List[List[Any]]):
        html = ['<div style="overflow-x:auto;"><table><thead><tr>']
        for h in headers:
            html.append(f'<th>{h}</th>')
        html.append('</tr></thead><tbody>')
        
        for row in rows:
            html.append('<tr>')
            for cell in row:
                val_str = str(cell)
                # Badge logic for Criticality
                badge_class = ""
                if val_str == "CRITICAL": badge_class = "badge bg-crit"
                elif val_str == "HIGH": badge_class = "badge bg-high"
                elif val_str == "MINIMAL": badge_class = "badge bg-ok"
                
                content = f'<span class="{badge_class}">{val_str}</span>' if badge_class else val_str
                html.append(f'<td>{content}</td>')
            html.append('</tr>')
            
        html.append('</tbody></table></div>')
        self.sections.append("".join(html))

    def generate(self) -> str:
        return HTML_TEMPLATE.format(
            title=self.title,
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            content="\n".join(self.sections)
        )