"""
Example: Running Simulations Programmatically
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parents[1]))

from src.infrastructure import Container
from src.application.services import SimulationService

def main():
    # Make sure Neo4j is running with data imported
    try:
        # Initialize container and repository
        container = Container()
        repo = container.graph_repository()
        
        with SimulationService(repo) as sim:
            # 1. Failure Sim (Simulate Node Failure)
            print("Simulating Node Failure (Node-0)...")
            # Using typical generated IDs: Node_0, App_0
            # Note: IDs depend on generation seed/logic. 
            # If fail, try catch specific IDs or just list components first.
            
            # Use 'Node_0' if generated by new generator, or 'N0' if older. 
            # Let's try to find a node.
            nodes = sim.graph.get_components_by_layer("infra")
            if nodes:
                target = nodes[0]
                print(f"Targeting: {target}")
                fail_res = sim.run_failure_simulation(target)
                print(f"Cascaded Failures: {len(fail_res.cascaded_failures)}")
            else:
                print("No nodes found to simulate failure.")
            
            # 2. Event Sim (Simulate App Publishing)
            print("\nSimulating Event...")
            apps = sim.graph.get_components_by_layer("app")
            if apps:
                source = apps[0]
                print(f"Source: {source}")
                event_res = sim.run_event_simulation(source)
                print(f"Reached Subscribers: {len(event_res.reached_subscribers)}")
            else:
                print("No applications found to simulate events.")
                
        container.close()
            
    except Exception as e:
        print(f"Error: {e}")
        print("Note: Ensure you have run 'import_graph.py' first.")

if __name__ == "__main__":
    main()