"""
Example: Importing Graph Data Programmatically
"""
import sys
import json
from pathlib import Path

# Add project root to sys.path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "backend"))

from src.core import create_repository

def main():
    # Use the file generated by example_generation.py
    input_file = Path("example_graph.json")
    
    if not input_file.exists():
        print(f"File {input_file} not found. Run example_generation.py first.")
        return

    try:
        print(f"Reading {input_file}...")
        with open(input_file) as f:
            data = json.load(f)

        print("Connecting to Neo4j...")
        # Initialize Repository (defaults to bolt://localhost:7687, user=neo4j, password=password)
        # You can pass arguments: create_repository(uri="...", user="...", password="...")
        repo = create_repository()
        
        try:
            print("Importing data into Neo4j (clearing existing data)...")
            repo.save_graph(data, clear=True)
            
            stats = repo.get_statistics()
            print("\nImport Complete!")
            print(f"  Nodes: {stats.get('node_count', 0)}")
            print(f"  Apps:  {stats.get('application_count', 0)}")
            print(f"  Relationships (RUNS_ON): {stats.get('runs_on_count', 0)}")
            print(f"  Relationships (PUBLISHES): {stats.get('publishes_to_count', 0)}")
            
        finally:
            repo.close()
            
    except Exception as e:
        print(f"Error: {e}")
        print("Ensure Neo4j is running.")

if __name__ == "__main__":
    main()
