/**
 * Shared tooltip definitions for technical terms displayed across the UI.
 * These appear as hover explanations (TermTooltip) next to metric names,
 * score labels, and architecture terminology.
 */

export const TERM_TOOLTIPS: Record<string, string> = {
  // ── RMAV Dimensions ────────────────────────────────────────────────────────
  "RMAV": "Reliability · Maintainability · Availability · Vulnerability — the four quality dimensions scored for every component.",
  "R(v)": "Reliability score — measures fault-propagation reach using Reverse PageRank, in-degree, and cascade depth potential. Higher = more likely to cause cascading failures.",
  "M(v)": "Maintainability score — measures structural bottleneck risk using betweenness centrality, efferent coupling, code quality, and clustering. Higher = harder to change safely.",
  "A(v)": "Availability score — measures connectivity disruption when this component fails, using articulation-point analysis, bridge ratio, and QoS-weighted SPOF severity. Higher = more likely to partition the network.",
  "V(v)": "Vulnerability score — measures adversarial attack reach using reverse eigenvector and closeness centrality on the transposed graph. Higher = higher-value attack target.",
  "Q(v)": "Overall quality score — weighted combination of R(v), M(v), A(v), V(v). Represents the component's total predicted impact if it fails. Q = 0.24·R + 0.17·M + 0.43·A + 0.16·V.",
  "Reliability": "Fault-propagation dimension — how far failures originating at this component spread through the system. Computed as R(v) = 0.45·RPR + 0.30·DG_in + 0.25·CDPot.",
  "Maintainability": "Change-impact dimension — how much a code or configuration change here ripples to other components. Computed as M(v) = 0.35·BT + 0.30·w_out + 0.15·CQP + 0.12·CouplingRisk + 0.08·(1−CC).",
  "Availability": "Connectivity-disruption dimension — how severely the network is partitioned when this component is removed. Computed as A(v) = 0.35·AP_c + 0.25·QSPOF + 0.25·BR + 0.10·CDI + 0.05·w(v).",
  "Vulnerability": "Attack-surface dimension — how accessible and influential this component is to adversarial compromise propagation. Computed as V(v) = 0.40·REV + 0.35·RCL + 0.25·QADS.",

  // ── Criticality Levels ─────────────────────────────────────────────────────
  "CRITICAL": "Score exceeds Q3 + 0.75×IQR of all components — statistically extreme risk. Treat as a top-priority architectural concern.",
  "HIGH": "Score exceeds Q3 (75th percentile) — above-average risk requiring attention.",
  "MEDIUM": "Score exceeds the median — moderate risk, worth monitoring.",
  "LOW": "Score exceeds Q1 (25th percentile) — below-average risk.",
  "MINIMAL": "Score at or below Q1 — minimal predicted impact.",
  "IQR": "Interquartile Range — the spread between the 25th and 75th percentiles, used to determine CRITICAL thresholds.",
  "Box-Plot": "Statistical classification method that sets criticality thresholds using quartiles and IQR of the score distribution, rather than fixed cut-offs.",

  // ── Metrics ────────────────────────────────────────────────────────────────
  "Spearman ρ": "Spearman rank-order correlation — measures how well the predicted scores rank components in the same order as simulation ground truth. Range −1 to +1; ≥ 0.87 is the validation target.",
  "Spearman": "Spearman rank-order correlation — measures how well predicted scores agree with simulation ground truth in ranking order. Target ρ ≥ 0.87.",
  "F1 Score": "Harmonic mean of Precision and Recall for CRITICAL component classification. Target F1 ≥ 0.90.",
  "F1": "Harmonic mean of Precision and Recall for CRITICAL component classification. Target F1 ≥ 0.90.",
  "Precision": "Fraction of predicted-CRITICAL components that are truly critical according to simulation.",
  "Recall": "Fraction of truly-critical components (by simulation) that were predicted as CRITICAL.",
  "RMSE": "Root Mean Squared Error between predicted scores Q(v) and simulation impact I(v). Lower is better.",
  "NDCG@10": "Normalised Discounted Cumulative Gain at rank 10 — measures how well the top-10 predicted components match the top-10 simulated components.",
  "Top-5 Overlap": "Number of components appearing in both the top-5 predicted list and the top-5 simulated-impact list.",
  "MAE": "Mean Absolute Error between predicted scores and simulation ground truth. Lower is better.",
  "CCR@5": "Cascade Capture Rate at 5 — fraction of the top-5 cascade-critical components correctly identified by R(v).",
  "COCR@5": "Change Overlap Capture Rate at 5 — fraction of the top-5 change-impact components correctly identified by M(v).",
  "SPOF_F1": "Single Point of Failure classification F1 — measures how accurately A(v) identifies true network SPOF components.",
  "RRI": "Robustness Rank Improvement — how much the RMAV ranking improves upon a random baseline in availability prediction.",
  "AHCR@5": "Attack Hit Capture Rate at 5 — fraction of the top-5 adversarial targets correctly identified by V(v).",
  "FTR": "False Trust Rate — fraction of components incorrectly classified as low-vulnerability when they are high-value attack targets.",
  "APAR": "Attack Path Agreement Rate — alignment between predicted vulnerability ranking and actual compromise propagation paths.",

  // ── Graph Metrics ──────────────────────────────────────────────────────────
  "Reverse PageRank": "PageRank computed on the transposed graph G^T — assigns higher scores to components with many downstream dependents, capturing fault propagation reach.",
  "RPR": "Reverse PageRank — PageRank on the transposed dependency graph; components with many dependents score higher.",
  "Betweenness Centrality": "Fraction of shortest paths between all node pairs that pass through this component — measures structural bottleneck position.",
  "Betweenness": "Fraction of shortest paths that pass through this component — a structural bottleneck measure.",
  "Reverse Eigenvector": "Eigenvector centrality on the transposed graph G^T — assigns higher scores to components connected to other influential components from an attacker's perspective.",
  "REV": "Reverse Eigenvector centrality — measures strategic attack reach by computing eigenvector centrality on G^T.",
  "Closeness": "Inverse of average shortest path length — how quickly a failure or compromise can reach all other nodes.",
  "RCL": "Reverse Closeness on G^T — measures adversarial propagation speed; closer components can compromise others faster.",
  "Articulation Point": "A node whose removal increases the number of disconnected components (network fragments). SPOFs are typically articulation points.",
  "AP_c": "Directional articulation-point score — max(out-direction score, in-direction score); captures both publisher and subscriber removal scenarios.",
  "Bridge": "An edge whose removal disconnects two previously connected parts of the graph — a structural SPOF at the edge level.",
  "Bridge Ratio": "Fraction of a component's incident edges that are bridges — high ratio means most connections are single-path.",
  "BR": "Bridge Ratio — fraction of incident edges that are bridges (single points of failure at the edge level).",
  "Clustering Coefficient": "Probability that a component's neighbours are also connected to each other — high clustering indicates redundant paths.",
  "CC": "Clustering Coefficient — measures local redundancy; lower values indicate more bottleneck-like positions.",
  "CDI": "Connectivity Degradation Index — normalised increase in average shortest-path length when this component is removed.",
  "CDPot": "Cascade Depth Potential — estimated maximum cascade depth from this component, weighted by multi-path coupling intensity (MPCI).",
  "MPCI": "Multi-Path Coupling Intensity — number of independent paths amplifying a potential cascade; scales CDPot.",
  "QSPOF": "QoS-Scaled SPOF Severity — AP_c multiplied by operational priority weight w(v); prioritises high-weight articulation points.",
  "QADS": "QoS-weighted Attack-Dependent Surface — inbound dependency weight w_in; measures how many high-priority upstream components expose this node.",
  "CQP": "Code Quality Penalty — composite of normalised cyclomatic complexity, Martin instability, and LCOM. Non-zero only when source-code metrics are present.",
  "LCOM": "Lack of Cohesion of Methods — measures how many unrelated responsibilities a class contains. Higher = worse cohesion.",
  "CouplingRisk": "Coupling Risk = 1 − |2·Instability − 1| — peaks at 0.5 instability; components that are both heavily depended-upon and depend on many others.",
  "Martin Instability": "I = Ce / (Ca + Ce) — ratio of efferent (outgoing) to total couplings. 0 = fully stable, 1 = fully unstable.",

  // ── Graph Structure ────────────────────────────────────────────────────────
  "SPOF": "Single Point of Failure — a component whose removal would disrupt service for a significant portion of the system.",
  "FAILURE_HUB": "Anti-pattern: a component with extremely high reliability risk — too many downstream dependents that would cascade-fail on its outage.",
  "GOD_COMPONENT": "Anti-pattern: a component that is both heavily connected and a structural bottleneck (high M(v) + high betweenness) — a maintenance nightmare.",
  "TARGET": "Anti-pattern: a component with critically high vulnerability score — a high-value adversarial target.",
  "BRIDGE_EDGE": "Anti-pattern: an edge whose removal disconnects the graph — a structural weak link.",
  "EXPOSURE": "Anti-pattern: a component with high vulnerability and high closeness centrality — easy to reach and compromise.",
  "CYCLE": "Anti-pattern: a strongly-connected component (SCC) of size ≥ 2 — circular dependencies that cause coupled failure and maintenance issues.",
  "HUB_AND_SPOKE": "Anti-pattern: a low-clustering, high-degree node — everything connects through this hub, creating a single bottleneck.",
  "CHAIN": "Anti-pattern: a long linear dependency chain (≥ 4 hops) — deep chains amplify cascade failures.",
  "SYSTEMIC_RISK": "Anti-pattern: more than 20% of system components are CRITICAL — a systemic architectural problem requiring broad redesign.",
  "SCC": "Strongly Connected Component — a maximal subgraph where every node can reach every other node. SCCs of size ≥ 2 indicate cyclic dependencies.",
  "density": "Graph density — ratio of actual edges to possible edges. 0 = sparse, 1 = fully connected.",
  "diameter": "Longest shortest path in the graph — the maximum number of hops needed to travel between any two nodes.",
  "avg_path_length": "Average shortest path length across all node pairs — lower values indicate a more compact, well-connected graph.",
  "num_components": "Number of weakly connected components — a value > 1 means the graph is fragmented into isolated sub-graphs.",
  "num_articulation_points": "Count of nodes whose removal would increase the number of disconnected components — each is a potential SPOF.",
  "num_bridges": "Count of edges whose removal would disconnect the graph — each is a potential single point of failure at the link level.",
  "avg_clustering": "Average clustering coefficient across all nodes — measures how often neighbours of a node are connected to each other.",
  "avg_degree": "Average number of edges per node — a proxy for connectivity density.",

  // ── Simulation ────────────────────────────────────────────────────────────
  "composite_impact": "I(v) — weighted combination of reachability loss, fragmentation, throughput loss, and flow disruption from removing component v. I = 0.35·reach + 0.25·frag + 0.25·thru + 0.15·flow.",
  "I(v)": "Simulation impact score — ground-truth measure of damage caused by removing component v. Used to validate Q(v) predictions.",
  "IR(v)": "Reliability ground truth — measures fault-propagation dynamics (cascade reach, weighted impact, depth) from v's removal.",
  "IM(v)": "Maintainability ground truth — measures change-propagation reach on the transposed dependency graph via BFS.",
  "IA(v)": "Availability ground truth — QoS-weighted connectivity disruption (reachability loss + fragmentation + path-breaking throughput loss).",

  // ── Traffic Simulator ─────────────────────────────────────────────────────
  "Publisher Count": "Number of application nodes actively publishing messages to this topic. Inbound rate = publisher_count × frequency_hz.",
  "Subscriber Count": "Number of application nodes subscribed to receive messages from this topic. Each published message is copied once per subscriber (fan-out).",
  "Topic Weight": "QoS-based operational priority weight, ∈ [0, 1]. Derived from reliability and durability QoS settings on the topic node. 0.0 = minimal priority · 1.0 = highest criticality.",
  "In (msg/s)": "Inbound message rate arriving at the broker: publisher_count × frequency_hz. Total messages over the window = In × duration_sec.",
  "Out (msg/s)": "Outbound fan-out rate leaving the broker: In (msg/s) × subscriber_count. The broker delivers one copy to every subscriber.",
  "Network Bandwidth": "Total estimated byte throughput across the entire simulation: sum of all topic bandwidths. Each topic = (inbound + outbound) × message_size_bytes. Colour scale: green (<20% max) · yellow (20–50%) · orange (50–80%) · red (>80% max).",
  "Inbound Rate": "Messages arriving at this broker per second from all publishers across its routed topics. Formula: Σ(publisher_count × Hz) over all routed topics.",
  "Outbound Rate": "Fan-out deliveries leaving this broker per second. Each inbound message is copied once per subscriber. Formula: Σ(inbound × subscriber_count) over all routed topics.",
  "Simulation Frequency": "How many messages each publisher sends per second (Hz). Applied per topic — override per topic by selecting it and editing the Hz field inline. Typical ranges: 1 Hz (slow telemetry) · 10 Hz (moderate control loop) · 100 Hz (high-frequency sensor).",
  "Simulation Duration": "Simulated time window in seconds. Affects total message counts but not bandwidth rates. Total messages = frequency × duration × publishers.",
  "Message Size": "Payload size per message in bytes (fallback 1 024 B = 1 KB). Sourced from the topic node in the graph. Affects bandwidth only — not message rates.",
  "Messages Published": "Total messages sent across all publishers: Σ(publisher_count × frequency_hz × duration_sec). This is the inbound side only.",
  "Messages Delivered": "Total fan-out deliveries received by all subscribers: Σ(published_per_topic × subscriber_count). Always ≥ Messages Published when any topic has multiple subscribers.",
  "Fan-out Multiplier": "subscriber_count / publisher_count per topic. A high fan-out (e.g. 10×) means one publisher drives significant broker outbound load. The delivered count in the summary reflects cumulative fan-out across all selected topics.",
  "Peak Topic Bandwidth": "Highest single-topic bandwidth in the simulation set. Useful as a reference for the colour scale — the busiest topic is always red.",
  "Broker Load": "Sum of inbound + outbound traffic across all topics routed by this broker. A topic routed by multiple brokers is counted in full for each — this is intentional: each broker independently carries the full load for every topic it routes.",
  "IV(v)": "Vulnerability ground truth — adversarial compromise propagation reach via BFS on G^T with trust threshold θ=0.30.",
  "reachability_loss": "Fraction of node-to-node shortest paths that are broken when this component is removed.",
  "fragmentation": "Percentage of components that become disconnected from the main component when this node is removed.",
  "throughput_loss": "Estimated percentage drop in message-routing throughput due to this component's failure.",
  "flow_disruption": "Fraction of event-simulation message flows that are interrupted by this component's failure.",
  "cascade": "Cascading failures triggered by removing this component — other components that fail as a consequence.",
  "cascade_probability": "Probability that a failure at this component triggers at least one further failure in the network.",
  "delivery_rate_percent": "Percentage of published messages that were successfully delivered to at least one subscriber.",
  "drop_rate_percent": "Percentage of published messages that were dropped (queue overflow, unreachable broker, deadline exceeded, etc.).",
  "avg_latency_ms": "Average end-to-end message latency in milliseconds for this simulation run.",
  "p50_latency_ms": "Median (50th percentile) message latency — half of messages were delivered within this time.",
  "p99_latency_ms": "99th-percentile message latency — 99% of messages were delivered within this time.",
  "throughput_per_sec": "Number of messages successfully delivered per second during the event simulation.",
  "Exhaustive Simulation": "Removes every component one-by-one and records the resulting impact — produces the ground-truth I(v) ranking for all components.",
  "Monte Carlo Simulation": "Randomly samples failure scenarios to estimate impact distribution — faster than exhaustive but less complete.",

  // ── GNN / Training ────────────────────────────────────────────────────────
  "GNN": "Graph Neural Network — learns node criticality directly from the graph topology using message-passing between neighbours.",
  "HeteroGAT": "Heterogeneous Graph Attention Network — a GNN variant that handles multiple node types (Application, Node, Broker, etc.) and learns separate attention weights per edge type.",
  "GAT": "Graph Attention Network — a GNN that uses learned attention weights to determine how much each neighbour influences a node's representation.",
  "ensemble_alpha": "α blending coefficient — weight given to GNN predictions vs. RMAV rule-based scores. Q_ensemble = α·Q_GNN + (1−α)·Q_RMAV.",
  "Hidden Dim": "Number of hidden features per node in each GNN layer — larger values capture more complex patterns but require more data.",
  "Attn Heads": "Number of parallel attention heads in the GAT layers — more heads allow the model to attend to different neighbourhood aspects simultaneously.",
  "GNN Layers": "Number of message-passing hops — each layer aggregates information from 1 hop further away in the graph.",
  "Dropout": "Fraction of neurons randomly deactivated during training — prevents overfitting by forcing the model to learn redundant representations.",
  "Learning Rate": "Step size for gradient descent during training — too large causes instability, too small causes slow convergence.",
  "Early-stop Patience": "Number of epochs without validation improvement before training stops — prevents overfitting by stopping training at the right time.",
  "Train Ratio": "Fraction of components used for training the GNN — remaining data is split between validation and test sets.",
  "Checkpoint": "Saved model weights from the best training epoch — used to restore and run inference without retraining.",
  "NDCG@10": "Normalised Discounted Cumulative Gain at rank 10 — measures ranking quality of top-10 components; 1.0 is perfect.",

  // ── Statistics ────────────────────────────────────────────────────────────
  "Topic Bandwidth": "Total estimated data throughput through a topic, computed from publishing frequency and message payload size.",
  "Pub/Sub Balance": "Ratio of publishers to subscribers on a topic — indicates whether a topic is broadcast-heavy (1→N), aggregation-heavy (N→1), or balanced.",
  "Topic Fanout": "Number of distinct subscribers receiving messages from a topic — high fanout means a topic failure impacts many consumers.",
  "Orphan Topic": "A topic with publishers but no subscribers, or subscribers but no publishers — a dead-end in the message flow.",
  "Cross-Node Heatmap": "Matrix showing the volume of inter-node communication — high off-diagonal values indicate tightly coupled infrastructure nodes.",
  "Node Communication Load": "Total message traffic (bytes/second) routed through a physical infrastructure node.",
  "Domain Communication": "Message flow volume between logical system domains or segments.",

  // ── Layers ────────────────────────────────────────────────────────────────
  "Application Layer": "Analyzes only Application and Library nodes — focuses on software component blast-radius risk.",
  "Infrastructure Layer": "Analyzes only Node (physical/virtual machine) components — focuses on hardware/deployment risk.",
  "Middleware Layer": "Analyzes Applications, Nodes, and Brokers together — captures full pub-sub communication risk.",
  "System Layer": "Full system analysis across all component types — provides the most complete picture.",

  // ── Node / Edge Types ──────────────────────────────────────────────────────
  "Application": "A software component that publishes or subscribes to topics via a message broker.",
  "Node": "A physical or virtual infrastructure node that hosts applications and brokers.",
  "Broker": "A message broker that routes pub-sub events between publishers and subscribers.",
  "Topic": "A named message channel — publishers write to it and subscribers read from it.",
  "Library": "A shared software library used by applications — library failures can simultaneously impact all consumers.",
  "DEPENDS_ON": "A derived dependency edge — emitted when component A can only function correctly if component B is operational.",
  "PUBLISHES_TO": "An edge from an Application to a Topic — the application sends messages to this channel.",
  "SUBSCRIBES_TO": "An edge from an Application to a Topic — the application receives messages from this channel.",
  "RUNS_ON": "An edge from an Application or Broker to a Node — the component is deployed on that infrastructure node.",
  "ROUTES": "An edge from a Broker to a Topic — the broker is responsible for delivering messages on this topic.",
  "USES": "An edge from an Application to a Library — the application depends on this library at runtime.",
  "CONNECTS_TO": "A physical connectivity edge between infrastructure nodes.",

  // ── AHP ───────────────────────────────────────────────────────────────────
  "AHP": "Analytic Hierarchy Process — a structured method for deriving relative weights (e.g., RMAV dimension weights) from pairwise importance comparisons.",
  "AHP Shrinkage": "Blends AHP-derived weights with a uniform prior using factor λ=0.7 — prevents extreme weight assignments and improves robustness.",

  // ── Statistics sub-pages ──────────────────────────────────────────────────
  "Degree Distribution": "Histogram of how many connections (edges) each component has — reveals hubs, isolated nodes, and overall connectivity balance.",
  "In-degree": "Number of incoming edges to a component — counts how many other components depend on it.",
  "Out-degree": "Number of outgoing edges from a component — counts how many components it depends on.",
  "Hub Node": "A component with degree far above the mean (> μ + 2σ) — acts as a central connector whose failure would disconnect many others.",
  "Isolated Node": "A component with no edges (degree = 0) — neither depends on nor is depended upon by any other component.",
  "Dependency Depth": "The longest chain of DEPENDS_ON edges leading to a component — deep dependencies amplify cascade failures.",
  "Transitive Dependency": "An indirect dependency through a chain of components — failure of a deep transitive dependency can propagate unexpectedly.",
  "Root Component": "A component with no outgoing dependencies (in-degree only) — an entry point or top-level consumer.",
  "Leaf Component": "A component with no incoming dependencies — a foundational service or library everything else builds on.",
  "Edge Weight": "A value ∈ [0,1] on a DEPENDS_ON edge representing the maximum QoS severity — higher weight means a more critical dependency.",
  "Node Weight": "A component's operational priority weight ∈ [0,1] — sourced from QoS attributes; higher means more business-critical.",
  "Component Isolation": "A component is 'isolated' when it has no dependencies (source) or no dependents (sink) in the DEPENDS_ON graph.",
  "Source Component": "A component with outgoing dependencies but no incoming ones — an entry-point that nothing else depends on.",
  "Sink Component": "A component with incoming dependencies but no outgoing ones — a foundation layer that all others depend on.",
  "Resilience Score": "A composite measure of redundancy — based on alternative paths available if key components fail.",
  "Network Density": "Ratio of actual edges to maximum possible edges in the graph. Sparse (<0.1), Moderate (0.1–0.3), Dense (>0.3).",
  "Edge Utilization": "Fraction of maximum possible edges that are actually present — same as network density.",
  "Broker Utilization": "Message load on a broker — fraction of total system traffic routed through it.",
  "Hot Topic": "A topic with unusually high message throughput or many publisher/subscriber connections — a potential bottleneck.",
  "Library Dependency Density": "Ratio of library-consuming edges to applications — high density means many apps share the same libraries (shared-fate risk).",
  "Node Critical Density": "Fraction of critical applications concentrated on a single infrastructure node — high density means a node failure takes down many critical components.",
  "Domain Diversity": "Variety of application and topic types within a system domain — low diversity indicates monolithic or tightly-scoped subsystems.",
}
